// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvPtzpC803lE7ZYeiJo-8cDaHJoRdORNc',
    appId: '1:498246911307:web:2799790669d54f267554ce',
    messagingSenderId: '498246911307',
    projectId: 'sitata-mata',
    authDomain: 'sitata-mata.firebaseapp.com',
    storageBucket: 'sitata-mata.firebasestorage.app',
    measurementId: 'G-65ZYQKHLMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTWkh678liARmWx490pBK1MnzRW1Ma2_s',
    appId: '1:498246911307:android:94944a993532f8f17554ce',
    messagingSenderId: '498246911307',
    projectId: 'sitata-mata',
    storageBucket: 'sitata-mata.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwjjwRH9m2XtN6tXlUASi89F9Go-mFoYg',
    appId: '1:498246911307:ios:81e2c825891342ac7554ce',
    messagingSenderId: '498246911307',
    projectId: 'sitata-mata',
    storageBucket: 'sitata-mata.firebasestorage.app',
    iosBundleId: 'com.example.simata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR-MACOS-API-KEY',
    appId: 'YOUR-MACOS-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'YOUR-PROJECT-ID',
    storageBucket: 'YOUR-STORAGE-BUCKET',
    iosClientId: 'YOUR-MACOS-CLIENT-ID',
    iosBundleId: 'YOUR-MACOS-BUNDLE-ID',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvPtzpC803lE7ZYeiJo-8cDaHJoRdORNc',
    appId: '1:498246911307:web:c282f1b80c9cb38a7554ce',
    messagingSenderId: '498246911307',
    projectId: 'sitata-mata',
    authDomain: 'sitata-mata.firebaseapp.com',
    storageBucket: 'sitata-mata.firebasestorage.app',
    measurementId: 'G-XNNPZZNQS5',
  );

}